# Data Processing I I

- Data understanding is made possible through data visualisation.
- We use numPy and pandas for data cleaning and data manipulation.

## NumPy

### Why Numpy?

- Quick answer: Numpy is Faster.

In [67]:
import numpy as np
import pandas as pd

a = np.array([1,2,3,4,5])
b = np.array((1,6,3,4,9))

print (a)
print (b)

[1 2 3 4 5]
[1 6 3 4 9]


In [68]:
np.__version__

'1.20.1'

In [69]:
pd.__version__

'1.2.3'

In [70]:
a = np.array([1,2,3,5,-8])
a.dtype

dtype('int32')

In [71]:
b = np.array((2,3,5,6,7,8))

In [72]:
l = [1,2,3,4,"abc",5]     #you can work with list *see below

In [73]:
type(a)

numpy.ndarray

In [74]:
type(l)

list

- the list is necessary when storing different data types like int and str

In [75]:
print (a)
a.ndim

[ 1  2  3  5 -8]


1

### Numpy (Dimensions)

- Sometimes objects inside n array can be arrays themselves, hence termed Dimensions

In [76]:
c = np.array([
    [1,2,3],
    [4,5,6]
])
print(c.ndim)

2


In [77]:
d = np.array([
    [
        [1,2,3],
        [4,5,6]
    ],
    [
        [1,2,3],
        [4,5,6]
    ]
])
print (d.ndim)

3


In [78]:
print(d.shape[0], d.shape[1], d.shape[2])
print (d[1,0,2])

2 2 3
3


In [79]:
A = np.array([
    [1,2,3,4],
    [3,5,-7,0]
])
A.ndim

#result is the count of how going deeper it is

2

In [80]:
B = np.array ([
    [
    [1,2,3,4],
    [3,4,5,8],
    [9,8,7,2]
],
[
    [5,2,3,4],
    [-3,4,-5,8],
    [9,8,-7,2]
]])

B.ndim

3

### Array Shapes
- Another property of arrays is shapes.
- Array shapes tell you how many nested structures you're going in and how many elements are there

In [81]:
B.shape       #there are 2 d arrays and inside there is 3d arrays with 4 elements

(2, 3, 4)

In [82]:
B.shape[0]           #prints the high level structure

2

In [83]:
B.shape [1]

3

In [84]:
B.shape [2]

4

### How to access elements in an array

In [85]:
B

array([[[ 1,  2,  3,  4],
        [ 3,  4,  5,  8],
        [ 9,  8,  7,  2]],

       [[ 5,  2,  3,  4],
        [-3,  4, -5,  8],
        [ 9,  8, -7,  2]]])

In [86]:
B[0,1,2]      

5

** in the above example 'B[[0,1,2]]' means: **
- pick the high level with index 0, inside the first structures pick the array with index 1, inside that array pick the number with index = 2

### Other Numpy functions include:

- np.arange
- np.randomm.permutation
- np.reshape


In [87]:
A = np.arange(10)
A
#this tells NumPy to generate an array with elements from 0 to 9.

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [88]:
B = np.arange(2,100,10)
B
#creates an array starting from 2 to 100 with 10 steps in between

array([ 2, 12, 22, 32, 42, 52, 62, 72, 82, 92])

In [89]:
np.random.permutation(np.arange(10))
#np.arange generates numbers from 0 to 9
#np.random will randomise the generated numbers

array([4, 6, 9, 5, 0, 3, 1, 7, 8, 2])

In [90]:
np.arange(100).reshape(25,4)

#in this example
#np.arange creates a 1 x 100 array (1d)
# .reshape reshapes it to a 25 X 4 (2d) array
#number of elements in two arrays must match

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35],
       [36, 37, 38, 39],
       [40, 41, 42, 43],
       [44, 45, 46, 47],
       [48, 49, 50, 51],
       [52, 53, 54, 55],
       [56, 57, 58, 59],
       [60, 61, 62, 63],
       [64, 65, 66, 67],
       [68, 69, 70, 71],
       [72, 73, 74, 75],
       [76, 77, 78, 79],
       [80, 81, 82, 83],
       [84, 85, 86, 87],
       [88, 89, 90, 91],
       [92, 93, 94, 95],
       [96, 97, 98, 99]])

### NumPy Slicing

- uses the notation [[start:end:step]]

In [91]:
# [1:5]   index 1 till 5 but not 5
# [:5]    index 0 till 5 but not 5
# [2:]    index 2 till end including last element
# [::-1]  from end till start (reverse the array)
# [::2]   from start till end every other element
# [::2,:] from every other row and all columns

In [92]:
import numpy as np 

In [93]:
A = np.random.permutation (np.arange(10))
A

array([0, 6, 5, 2, 4, 3, 9, 8, 1, 7])

In [94]:
A[1:5]

array([6, 5, 2, 4])

In [95]:
A[1:7:2]

array([6, 2, 3])

In [96]:
A[::-1]    #reverses the array

array([7, 1, 8, 9, 3, 4, 2, 5, 6, 0])

In [97]:
A = np.arange(20).reshape(5,4)

In [98]:
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [99]:
A[2,3]    #row with index 2 and element in column with index 3

11

In [100]:
 A[1:3,2]      #from rows with index 1 and 2 access column elements with index 2

array([ 6, 10])

In [101]:
  A[1:3,1:3]   #from rows with index 1 to 3 access elements in columns  with index 1 to 3

array([[ 5,  6],
       [ 9, 10]])

In [102]:
A[1:3,:]   #from rows with index 1 to 3 select all elements in the columns

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [103]:
A[::2,:]  #from every other elements in all rows select all elements in all the columns

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [16, 17, 18, 19]])

In [104]:
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

 ### Numpy (More Indexing)

A[[index_array]]
>    instead of giving indices you can give an array of indices

- a[[[1,4,6]]]      
>    index 1, 4 and 6 elements will be returned. 

- a[[[True, True,False,False,True,True,True,False]]]

>   Assumming array has 8 elements,  the above returns all the elements corresponding to True index, the False elements wont be returned.

- a[[a<8]]
>This creates a Boolean list, True if it is less than 8 and False if it is more than 8

- a[[a<8 & a>4]]    
>difference between (and,&)?
> you can combine different logical operators

- a[[a<8 and a>4]]
>'and' is used when working with objects and not with indices

### Copy and View

- When you create an array of indices a copy of the array is made which contains elements

In [105]:
A = np.random.permutation(np.arange(10))
A

array([7, 4, 3, 8, 0, 5, 6, 2, 1, 9])

In [106]:
A[[1,5,2]]

array([4, 5, 3])

In [107]:
A<5

array([False,  True,  True, False,  True, False, False,  True,  True,
       False])

In [108]:
idx = A<5
A[idx]
#it generates elements rather than boolean

array([4, 3, 0, 2, 1])

In [109]:
A[A<5]   
#can be accessed without calling a variable


array([4, 3, 0, 2, 1])

In [110]:
A[(A<5) & (A>2)]

array([4, 3])

In [111]:
A

array([7, 4, 3, 8, 0, 5, 6, 2, 1, 9])

In [112]:
B = A[1:5]
B      #B is a subset of A

array([4, 3, 8, 0])

In [113]:
B[2]= -100
B
#changed element with index 2

array([   4,    3, -100,    0])

In [114]:
A
# a change in array B causes a change in array A

array([   7,    4,    3, -100,    0,    5,    6,    2,    1,    9])

In [115]:
B[2]= 3
B

array([4, 3, 3, 0])

In [116]:
A

array([7, 4, 3, 3, 0, 5, 6, 2, 1, 9])

In [117]:
B = A[1:5].copy()
B
#now B is a copy of A rather than a subset of A, any changes in B does not change A

array([4, 3, 3, 0])

In [118]:
B = A[A<5]
B
#by default this is a copy

array([4, 3, 3, 0, 2, 1])

In [119]:
B[0] = 999
B

array([999,   3,   3,   0,   2,   1])

In [120]:
A
#no change happened

array([7, 4, 3, 3, 0, 5, 6, 2, 1, 9])

### Behavior of Numpy

- If you use index, then you dont get a copy 

- If you use slicing, you automatically get a copy

### Numpy (Broadcasting)


- If you want to add a number in an array, all arrays should be of the same size eg:
> [[1,2,3]] + [[5,5,5]]

- Broadcasting is somewhat the same way. It adds every number in an array with the provided number.

- Care must be taken when broadcasting because there number of rows and columns should match the number of colums and rows.

In [121]:
A = A + 5
A


array([12,  9,  8,  8,  5, 10, 11,  7,  6, 14])

In [122]:
B = np.arange (20).reshape(5,4)
B

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [123]:
B.shape

(5, 4)

In [124]:
C = np.arange(5).reshape(5,1)
C

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [125]:
B + C

array([[ 0,  1,  2,  3],
       [ 5,  6,  7,  8],
       [10, 11, 12, 13],
       [15, 16, 17, 18],
       [20, 21, 22, 23]])

#### __Numpy (hstack, vstack,sort(axis=0))__

- if you want to concatenate two arrays horizontally we use np.hstack

- if you want to stack arrays vertically you can use np.vstack

- there are a lot of sort functions

-  you can use x = 0 to map your arrays
